<a href="https://colab.research.google.com/github/omarmoh26/BE-Alert/blob/main/Our_Dataset_Implementation_with_statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
import pandas_profiling as pp

# data = pd.read_csv('/content/gdrive/My Drive/adhamsleepy.csv')
# data1 = pd.read_csv('/content/gdrive/My Drive/anything.csv')
# data2 = pd.read_csv('/content/gdrive/My Drive/momsleepy.csv')
# data3 = pd.read_csv('/content/gdrive/My Drive/meawake.csv')
# data4 = pd.read_csv('/content/gdrive/My Drive/submission2.csv')
dataset=pd.read_csv('/content/gdrive/My Drive/acquiredDatasetStatistics.csv')

In [ ]:
dataset.head()


Attention_mean  Attention_median  Attention_mode  Attention_range  \
0       31.700000              29.5       32.000000             80.0   
1       43.900000              47.0       40.666667             92.0   
2       41.733333              40.0       40.000000             73.0   
3       41.816667              41.0       28.666667             67.0   
4       51.116667              50.0       45.200000             67.0   

   Attention_std  Attention_var  Attention_IQR     Theta_mean  Theta_median  \
0      17.373563     301.840678          20.75   72647.333333       44971.5   
1      19.731846     389.345763          26.50   48285.483333       36717.0   
2      15.941489     254.131073          20.00   67913.450000       41240.0   
3      17.417595     303.372599          26.00   89957.316667       49925.0   
4      14.845066     220.375989          19.25  124874.066667       69879.5   

      Theta_mode  ...    Alpha1_var  Alpha1_IQR   Alpha2_mean  Alpha2_median  \
0   72647.333333  ...  6.193477e+08    28910.25  30511.250000        28166.5   
1   48285.483333  ...  5.307118e+08    15023.25  21963.583333        17712.5   
2   67913.450000  ...  4.488679e+08    19689.75  28482.483333        22845.5   
3   89957.316667  ...  9.062865e+08    23600.00  24876.283333        12718.0   
4  124874.066667  ...  2.762353e+09    34400.50  33726.050000        21353.5   

    Alpha2_mode  Alpha2_range    Alpha2_std    Alpha2_var  Alpha2_IQR  \
0  30511.250000      126304.0  23364.910194  5.459190e+08    27869.25   
1  21963.583333       76285.0  16999.893442  2.889964e+08    19321.00   
2  28482.483333      134396.0  23611.017878  5.574802e+08    24742.25   
3  24876.283333      132706.0  28208.102450  7.956970e+08    28127.75   
4  33726.050000      195119.0  37984.086632  1.442791e+09    34557.00   

   classification  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0  

[5 rows x 29 columns]

In [ ]:
dataset['classification'] = dataset['classification'].astype(int)

In [ ]:
dataset.head()


Attention_mean  Attention_median  Attention_mode  Attention_range  \
0       31.700000              29.5       32.000000             80.0   
1       43.900000              47.0       40.666667             92.0   
2       41.733333              40.0       40.000000             73.0   
3       41.816667              41.0       28.666667             67.0   
4       51.116667              50.0       45.200000             67.0   

   Attention_std  Attention_var  Attention_IQR     Theta_mean  Theta_median  \
0      17.373563     301.840678          20.75   72647.333333       44971.5   
1      19.731846     389.345763          26.50   48285.483333       36717.0   
2      15.941489     254.131073          20.00   67913.450000       41240.0   
3      17.417595     303.372599          26.00   89957.316667       49925.0   
4      14.845066     220.375989          19.25  124874.066667       69879.5   

      Theta_mode  ...    Alpha1_var  Alpha1_IQR   Alpha2_mean  Alpha2_median  \
0   72647.333333  ...  6.193477e+08    28910.25  30511.250000        28166.5   
1   48285.483333  ...  5.307118e+08    15023.25  21963.583333        17712.5   
2   67913.450000  ...  4.488679e+08    19689.75  28482.483333        22845.5   
3   89957.316667  ...  9.062865e+08    23600.00  24876.283333        12718.0   
4  124874.066667  ...  2.762353e+09    34400.50  33726.050000        21353.5   

    Alpha2_mode  Alpha2_range    Alpha2_std    Alpha2_var  Alpha2_IQR  \
0  30511.250000      126304.0  23364.910194  5.459190e+08    27869.25   
1  21963.583333       76285.0  16999.893442  2.889964e+08    19321.00   
2  28482.483333      134396.0  23611.017878  5.574802e+08    24742.25   
3  24876.283333      132706.0  28208.102450  7.956970e+08    28127.75   
4  33726.050000      195119.0  37984.086632  1.442791e+09    34557.00   

   classification  
0               0  
1               0  
2               0  
3               0  
4               0  

[5 rows x 29 columns]

In [ ]:
data1 = dataset[['Theta_IQR','Alpha1_IQR','Alpha2_mean']]

In [ ]:
data1.head()

Attention_median     Theta_mean  Theta_IQR     Theta_mode   Alpha1_mean  \
0              29.5   72647.333333   72656.25   72647.333333  27699.650000   
1              47.0   48285.483333   38973.00   48285.483333  18966.533333   
2              40.0   67913.450000   71587.25   67913.450000  19579.083333   
3              41.0   89957.316667   73236.25   89957.316667  22844.183333   
4              50.0  124874.066667  128886.75  124874.066667  36195.600000   

   Alpha1_median  Alpha1_IQR   Alpha2_mean  Alpha2_median   Alpha2_mode  
0        23318.5    28910.25  30511.250000        28166.5  30511.250000  
1        13990.0    15023.25  21963.583333        17712.5  21963.583333  
2        10750.5    19689.75  28482.483333        22845.5  28482.483333  
3        13700.5    23600.00  24876.283333        12718.0  24876.283333  
4        18721.0    34400.50  33726.050000        21353.5  33726.050000

In [ ]:
y=dataset['classification']
# data1=data1.drop(columns=['attention'])
data1.head()

Attention_median     Theta_mean  Theta_IQR     Theta_mode   Alpha1_mean  \
0              29.5   72647.333333   72656.25   72647.333333  27699.650000   
1              47.0   48285.483333   38973.00   48285.483333  18966.533333   
2              40.0   67913.450000   71587.25   67913.450000  19579.083333   
3              41.0   89957.316667   73236.25   89957.316667  22844.183333   
4              50.0  124874.066667  128886.75  124874.066667  36195.600000   

   Alpha1_median  Alpha1_IQR   Alpha2_mean  Alpha2_median   Alpha2_mode  
0        23318.5    28910.25  30511.250000        28166.5  30511.250000  
1        13990.0    15023.25  21963.583333        17712.5  21963.583333  
2        10750.5    19689.75  28482.483333        22845.5  28482.483333  
3        13700.5    23600.00  24876.283333        12718.0  24876.283333  
4        18721.0    34400.50  33726.050000        21353.5  33726.050000

In [ ]:
scaler = StandardScaler()
X=scaler.fit_transform(data1)
print(X)

[[-5.35923494e-01 -1.64102415e-01 -4.63369618e-03]
 [-8.29042850e-01 -8.42175386e-01 -2.98620759e-01]
 [-5.45226177e-01 -6.14320016e-01 -7.44107683e-02]
 [-5.30876201e-01 -4.23390742e-01 -1.98441827e-01]
 [-4.65928047e-02  1.03974932e-01  1.05935614e-01]
 [ 2.73736246e-01  5.00066812e-01 -1.78747506e-02]
 [-6.78371214e-02  3.09808921e-01 -6.69283888e-02]
 [-8.97940573e-01 -1.06374416e+00 -2.03952457e-02]
 [-9.81843114e-01 -1.09428601e+00 -1.35713772e-01]
 [-8.85681308e-01 -1.05464997e+00 -9.69073683e-03]
 [-3.55208655e-01 -6.10902064e-01 -5.13785743e-01]
 [-7.13814460e-01 -1.03724282e+00 -3.15847486e-01]
 [-6.54463083e-01 -8.11047603e-01 -6.57140407e-01]
 [-5.56793615e-01 -9.77294377e-01 -5.10518329e-01]
 [-3.38527414e-02 -2.20462012e-01  2.34872790e-02]
 [ 2.57834974e+00  5.12749858e-01  3.54023371e+00]
 [ 4.52563882e+00 -6.38721756e-01  6.51019608e+00]
 [ 7.01476909e-01  3.00490118e+00  4.97902696e-01]
 [ 4.95421179e-01  6.99577589e-01  1.37624213e-02]
 [ 1.10955271e+00  1.00705905e+

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing


In [ ]:
x_train, x_test, y_train, y_test=train_test_split(X,y,test_size=0.3)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:

# from sklearn.linear_model import LogisticRegression
grid={"C":np.logspace(-3,3,7), "penalty":["l1","l2"]}# l1 lasso l2 ridge
logreg=LogisticRegression()
logreg_cv=GridSearchCV(logreg,grid,cv=10)
logreg_cv.fit(x_train,y_train)



/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
70 fits failed out of a total of 140.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
70 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py", line 447, in _check_solver
    raise ValueError(
ValueError: Solver 

GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),
                         'penalty': ['l1', 'l2']})

In [ ]:
print("tuned hpyerparameters :(best parameters) ",logreg_cv.best_params_)
logregAccuracy = logreg_cv.best_score_ *100
print("Accuracy for our training dataset with tuning is : {:.2f}%".format(logregAccuracy) )

tuned hpyerparameters :(best parameters)  {'C': 0.1, 'penalty': 'l2'}
Accuracy for our training dataset with tuning is : 73.00%


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, plot_confusion_matrix

In [ ]:
knn = KNeighborsClassifier()
# from sklearn.model_selection import GridSearchCV
k_range = [1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31]
param_grid = dict(n_neighbors=k_range)
  
# defining parameter range
grid = GridSearchCV(knn, param_grid, cv=10, scoring='accuracy', return_train_score=False,verbose=1)
  
# fitting the model for grid search
grid_search=grid.fit(x_train, y_train)

Fitting 10 folds for each of 16 candidates, totalling 160 fits


In [ ]:
print(grid_search.best_params_)

{'n_neighbors': 9}


In [ ]:
accuracy = grid_search.best_score_ *100
print("Accuracy for our training dataset with tuning is : {:.2f}%".format(accuracy) )

Accuracy for our training dataset with tuning is : 77.50%


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(random_state=42)
param_grid = { 
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [4, 5, 6, 7, 8],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [200, 500]})

In [ ]:
print(CV_rfc.best_params_)
accuracy = CV_rfc.best_score_ *100
print("Accuracy for our training dataset with tuning is : {:.2f}%".format(accuracy) )

{'criterion': 'gini', 'max_depth': 4, 'max_features': 'auto', 'n_estimators': 200}
Accuracy for our training dataset with tuning is : 72.22%


In [ ]:
from sklearn.svm import SVC


In [ ]:
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf','polynomial']} 
              # ,'linear','sigmoid'
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid.fit(x_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.556 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.556 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.556 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.556 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.625 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=1, kernel=polynomial;, score=nan total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=1, kernel=polynomial;, score=nan total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=1, kernel=polynomial;, score=nan total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=1, kernel=polynomial;, score=nan total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=1, kernel=polynomial;, score=nan total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.556 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
125 fits failed out of a total of 250.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
125 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py", line 255, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py", line 315, in _dense_fit
    ) = libsvm.fit(
  File "sklearn/svm/_libsvm.pyx", line 173, in

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf', 'polynomial']},
             verbose=3)

In [ ]:
print(grid.best_params_)

{'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}


In [ ]:
accuracy = grid.best_score_ *100
print("Accuracy for our training dataset with tuning is : {:.2f}%".format(accuracy) )

Accuracy for our training dataset with tuning is : 70.00%


In [ ]:
param_grid_full = [
  {'kernel': ['linear'], 'C': [0.1, 1, 10, 100, 1000]},
  {'kernel': ['sigmoid'], 'C': [0.1, 1, 10, 100, 1000], 
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
 ]

grid_full = GridSearchCV(SVC(), param_grid_full, cv = 10, scoring='accuracy') 
grid_full.fit(x_train, y_train) 

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [0.1, 1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [0.1, 1, 10, 100, 1000],
                          'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                          'kernel': ['sigmoid']}],
             scoring='accuracy')

In [ ]:
print(grid_full.best_params_)


{'C': 10, 'gamma': 0.1, 'kernel': 'sigmoid'}


In [ ]:
grid_predictions = grid_full.predict(x_test) 
print('Accuracy: {:.2f}'.format(accuracy_score(y_test, grid_predictions)))

Accuracy: 0.79
